amzn/amazon-payments-magento-2-plugin

composer.json
marketplace-composer.json
src/Payment/composer.json
src/Payment/view/frontend/web/js/amazon-core.js

Replaced Promise with jQuery Deferred - removed irritating error output

---

src/Payment/i18n/de_AT.csv
src/Payment/i18n/de_CH.csv
src/Payment/i18n/de_DE.csv
src/Payment/i18n/en_GB.csv
src/Payment/i18n/en_US.csv
src/Payment/i18n/es_AR.csv
src/Payment/i18n/es_CL.csv
src/Payment/i18n/es_CO.csv
src/Payment/i18n/es_CR.csv
src/Payment/i18n/es_ES.csv
src/Payment/i18n/es_MX.csv
src/Payment/i18n/es_PA.csv
src/Payment/i18n/es_PE.csv
src/Payment/i18n/es_VE.csv
src/Payment/i18n/fr_CA.csv
src/Payment/i18n/fr_FR.csv
src/Payment/i18n/it_CH.csv
src/Payment/i18n/it_IT.csv
src/Payment/view/frontend/web/template/checkout-revert.html

missing translation added

---

src/Core/etc/adminhtml/system.xml

change sortorder to avoid conflicts with core payment options

---

src/Payment/view/frontend/layout/checkout_index_index.xml

Changing layout to checkout, according to Magento 2.1 value

---

src/Payment/view/frontend/templates/minicart-button.phtml

Fixes pay buttons not rendering.
For some reason a template required for #12 is not present. This is the required template.

Add missing template

---

docs/customisation.rst
docs/prerequisites.rst

Removes warnings when creating the documentation

Documentation warnings

---

src/Core/Helper/Data.php
src/Core/etc/adminhtml/system.xml
src/Payment/Helper/Email.php
src/Payment/Model/OrderInformationManagement.php
src/Payment/view/frontend/email/hard-declined-auth.html
src/Payment/view/frontend/email/soft-declined-auth.html

AMAZON-17: Add configuration option for "Store Name"

---

src/Core/Domain/AmazonAddress.php
src/Core/Domain/AmazonAddressJp.php
src/Core/Domain/AmazonCustomerFactory.php
src/Core/Domain/AmazonCustomerJp.php
src/Core/Domain/AmazonName.php
src/Core/Domain/AmazonNameFactory.php
src/Core/Domain/AmazonNameJp.php
src/Core/etc/di.xml
src/Login/Controller/Login/Authorize.php
src/Login/Controller/Login/Guest.php

Hi,
I added country specific class mapping for JP. Of course it can use for other countries.
How about these codes?

Jp2016102402

---

src/Payment/Observer/CompleteOrder.php

Fixes #56 
This update changes the control flow without changing any of the functionality.
It prevents `if ($order->getState() == Order::STATE_COMPLETE && $order->getStoredData()[OrderInterface::STATE] != Order::STATE_COMPLETE) {` from executing in case Payment method is not Amazon, thus solving the issue where above line assumed certain array index exists.
Now the Observer executes it's own relevant code only when payment method = amazon, which should have been the case from the beginning.

Code safety update

---

src/Login/etc/adminhtml/system.xml

Make this option available for stores as well

Update scope to store level

---

src/Core/Block/Adminhtml/System/Config/Form/Version.php

#74 temporarily fixed until we have a better logic

temporary fix to display the correct version

---

src/Login/Model/Customer/Account/Redirect.php

Improves evaluation of the redirect URLs

change order of redirectURL evaluation

---

src/Payment/Block/Minicart/Button.php

Fixes button on cart not loading, depending on configuration.
short term fix.

Cart button fix

---

src/Core/Block/Adminhtml/System/Config/Form/SimplepathConfig.php
src/Core/Block/Adminhtml/System/Config/SimplePathAdmin.php
src/Core/Model/Config/SimplePath.php

Fixes #90 by removing unneeded code.

Fix compiliation dependency injections

---

docs/installation.rst

updated documentaton for installation and un-install

---

composer.json
marketplace-composer.json
src/Core/Block/Adminhtml/System/Config/Form/Version.php
src/Core/composer.json
src/Login/composer.json
src/Payment/Helper/Data.php
src/Payment/composer.json

1.1.3 version upgrade

---

src/Payment/i18n/de_AT.csv
src/Payment/i18n/de_CH.csv
src/Payment/i18n/de_DE.csv
src/Payment/i18n/en_GB.csv
src/Payment/i18n/en_US.csv
src/Payment/i18n/es_AR.csv
src/Payment/i18n/es_CL.csv
src/Payment/i18n/es_CO.csv
src/Payment/i18n/es_CR.csv
src/Payment/i18n/es_ES.csv
src/Payment/i18n/es_MX.csv
src/Payment/i18n/es_PA.csv
src/Payment/i18n/es_PE.csv
src/Payment/i18n/es_VE.csv
src/Payment/i18n/fr_CA.csv
src/Payment/i18n/fr_FR.csv
src/Payment/i18n/it_CH.csv
src/Payment/i18n/it_IT.csv
src/Payment/view/frontend/layout/checkout_index_index.xml
src/Payment/view/frontend/templates/minicart-button.phtml

Fixes #98  .
Verified all strings being translatable and updated a location which has been missed.

Verified and updated all translations of the extension

---

src/Login/view/frontend/web/js/amazon-redirect.js

loading animation on redirect

---

composer.json
marketplace-composer.json
src/Core/Client/Client.php
src/Core/Client/ClientFactory.php
src/Core/Client/ClientFactoryInterface.php
src/Core/Model/Validation/ApiCredentialsValidator.php
src/Core/composer.json
src/Core/etc/di.xml
src/Payment/Domain/AbstractAmazonAuthorizationResponse.php
src/Payment/Domain/AbstractAmazonCaptureResponse.php
src/Payment/Domain/AbstractAmazonRefundResponse.php
src/Payment/Domain/AmazonGetOrderDetailsResponse.php
src/Payment/Domain/AmazonRefundResponse.php
src/Payment/Domain/AmazonSetOrderDetailsResponse.php
src/Payment/Ipn/IpnHandler.php
src/Payment/Ipn/IpnHandlerFactory.php
src/Payment/Ipn/IpnHandlerFactoryInterface.php
src/Payment/Ipn/MockIpnHandler.php
src/Payment/Model/AddressManagement.php
src/Payment/Model/OrderInformationManagement.php
src/Payment/etc/di.xml

Fixes internal ticket IKL-694-88424

AMAZON-45: Upgrade dep. module amazon-pay-sdk-php from 2.1 to 3.1

---

src/Payment/Observer/CompleteOrderStatus.php

PR for the issue https://github.com/amzn/amazon-payments-magento-2-plugin/issues/115

Set correct order status in CompleteOrderStatus

---

composer.json
docs/installation.rst
marketplace-composer.json
src/Core/composer.json
src/Core/etc/module.xml
src/Login/composer.json
src/Payment/composer.json

New release version 1.1.4.
Compilation and checks passed.

Version 1.1.4

---

src/Payment/Helper/Email.php

Fixed wrong property name in Email.php

---

composer.json
marketplace-composer.json
src/Core/composer.json
src/Core/etc/module.xml
src/Login/composer.json
src/Payment/composer.json

preparing version 1.1.5

---

src/Payment/Model/ResourceModel/PendingRefund.php

correction of refund table name. Fixes #139.

---

src/Payment/Helper/Data.php
src/Payment/Model/OrderInformationManagement.php

This Pull Request consolidates Core and Payment get extension version methods. Payment now uses Core method.

Payment OrderInformationManagement now uses Core getVersion method

---

src/Payment/Observer/CompleteOrder.php

Fixes for 109 issue.

---

docs/configuration.rst

documentation updated

---

composer.json
docs/installation.rst
marketplace-composer.json
src/Core/composer.json
src/Core/etc/module.xml
src/Login/composer.json
src/Payment/composer.json

Extension version 1.2.0

---

composer.json
docs/installation.rst
marketplace-composer.json
src/Core/composer.json
src/Core/etc/module.xml
src/Login/composer.json
src/Payment/composer.json

Preparation of version 1.2.2

---

docs/installation.rst

small typos / misspellings. haha

---

src/Core/etc/di.xml

Fixes DI type declarations which use interfaces instead of implementations

Use implementations instead of interfaces

---

src/Core/view/frontend/templates/amazon_payments_mark.phtml
src/Core/view/frontend/templates/config.phtml
src/Login/view/frontend/templates/form/validate.phtml
src/Login/view/frontend/templates/login.phtml
src/Payment/view/frontend/templates/minicart-button.phtml
src/Payment/view/frontend/templates/payment-link-product-page.phtml
src/Payment/view/frontend/templates/payment-link.phtml

Replaced escapeNotVerified annotations with noEscape annotation where needed
escaped template urls with $block->escapeUrl()-s where needed

Escapes and annotations

---

composer.json
marketplace-composer.json

Simplify management of dependencies

dependencies only in composer of submodules

---

docs/faq.rst
docs/index.rst

Theme FAQ in documentation

---

src/Core/view/adminhtml/templates/system/config/simplepath_admin.phtml
src/Core/view/frontend/templates/config.phtml
src/Login/view/frontend/web/js/view/login-button-wrapper.js
src/Payment/view/frontend/web/js/amazon-widgets-loader.js
src/Payment/view/frontend/web/js/model/amazonPaymentConfig.js
src/Payment/view/frontend/web/js/view/checkout-revert.js
src/Payment/view/frontend/web/js/view/checkout-sandbox-simulator.js
src/Payment/view/frontend/web/js/view/checkout-widget-address.js
src/Payment/view/frontend/web/js/view/notification.js
src/Payment/view/frontend/web/js/view/payment/method-renderer/amazon-payment-widget.js

Changing global state of 'window' is forbidden, the UI registry should be used instead

Extension now uses uiRegistry instead of window global state

---

src/Core/etc/module.xml
src/Login/Controller/Login/Authorize.php
src/Login/etc/module.xml
src/Payment/etc/module.xml

Fixes #184 by updating module dependency order to prevent error on new store view/website creation.

Fix #184 - unable to create store view

---

src/Core/etc/module.xml

Removing additional unnecessary entry in module.xml. Fixes #184.

Update re: AP-279 removed reference to Magento_Vault in module.xml

---

docs/configuration.rst

Extend payment region information

---

src/Core/Helper/Data.php
src/Core/Model/Config/SimplePath.php
src/Core/etc/adminhtml/system.xml
src/Core/etc/config.xml
src/Core/view/frontend/templates/config.phtml
src/Payment/view/frontend/web/js/amazon-widgets-loader.js
src/Payment/view/frontend/web/js/view/checkout-revert.js
src/Payment/view/frontend/web/js/view/checkout-sandbox-simulator.js
src/Payment/view/frontend/web/js/view/checkout-widget-address.js

Added fixes to address Github issues #207 and #209

Support issue 207 209

---

src/Core/Setup/UpgradeData.php

UpgradeData script was not using Magento idomatic method of updating a table and so failed when tables had prefixes.

Update re: AP-359 - fixed update script

---

src/Login/Helper/Session.php
src/Login/view/frontend/web/js/amazon-csrf.js
src/Login/view/frontend/web/js/amazon-logout.js
src/Login/view/frontend/web/js/amazon-redirect.js

Applies fix from 1.2.6 - Github issue #104 and issue #105 - caused by checkout session not being updated on login and stale amazon payment token not being removed on logout.

Update re: APS-10 - Github issue #104

---

src/Core/Setup/UpgradeData.php
src/Login/Helper/Session.php
src/Login/view/frontend/web/js/amazon-logout.js
src/Payment/Model/OrderInformationManagement.php
src/Payment/Observer/ConfirmOrder.php
src/Payment/etc/di.xml

Issues addressed:
BUNDLE-1420 | Product doesn't add to cart

Merging pre-2.0.0 to magento-test

---

src/Payment/view/frontend/layout/checkout_index_index.xml
src/Payment/view/frontend/web/css/source/_module.less

Changed location of link and font size of logout link on checkout/amazon wallet page.

Update re: AP-362

---

src/Login/Model/CustomerLinkManagement.php

Removed CustomerSession Class that was causing infinite loop.  Tested on B2B/EE.

Restored fixes from prior build that removes CustomerSession class

---

src/Core/Block/Config.php
src/Payment/view/frontend/layout/checkout_index_index.xml
src/Payment/view/frontend/web/css/source/_module.less

Restores original layout configuration for checkout page and removes css to decrease link font size.

Update - reverts updates to AP wallet that added logout link below .

---

src/Core/view/adminhtml/templates/system/config/simplepath_admin.phtml

Added check on suspected null/missing element before validate is called.

Issue AP-379 

---

src/Login/Controller/Login/Guest.php

Correctly replaces protected with private modifier for internal class methods and properties.
Removed php docblock above class as it does not follow M2 standards.

Added correct method and property modifiers to Guest class

---

src/Login/composer.json
src/Payment/composer.json

Fixes dependency issue with Login and Payment sub-modules.

Updating dependency requirements for composer files

---

src/Payment/Model/PaymentManagement/Capture.php
src/Payment/view/frontend/web/js/amazon-button.js
src/Payment/view/frontend/web/js/amazon-widgets-loader.js

Enables multi-store settings with AP.

Added fix from APS-20 to 3x

---

src/Payment/view/frontend/web/js/amazon-button.js
src/Payment/view/frontend/web/js/amazon-widgets-loader.js

Enables multi-store settings with AP.

APS-20 fix for 2.x branch

---

src/Core/view/adminhtml/templates/system/config/simplepath_admin.phtml

Adds behavior/fix from 3.x branch to 2.x

Re: AP-380

---

src/Payment/etc/di.xml

Removed reference to Mail class in di.xml that was preventing from field from formatting properly.

Update re: AP-396

---

src/Payment/etc/di.xml

Removed reference to Mail class in di.xml that was preventing from field from formatting properly.

Update re: APS-30

---

src/Payment/etc/di.xml

Update - removed reference to Mail class in 1.2.6 di.xml file

APS-30 for 1.2.6

---

composer.json
marketplace-composer.json
src/Core/composer.json
src/Core/etc/module.xml
src/Login/composer.json
src/Payment/composer.json

Changes version from 3.0.0 to 2.1.0

Version change to 2.1.0

---

composer.json
src/Core/composer.json
src/Login/composer.json
src/Payment/composer.json

JSON files need to have 1 empty line at the end of file. There was also an unnecessary comma in one of the files that I cleaned up.

Update - added end line to each JSON file

---

src/Login/etc/module.xml
src/Payment/etc/module.xml

The login and payment module.xml documents were still version 3.0 - this PR changes those documents to version 2.1

Support issue 405 a

---

src/Core/Helper/Data.php

Removing comments in Core/Helper/Data.php

---

src/Login/Controller/Login.php
src/Login/Controller/Login/Authorize.php
src/Login/Controller/Login/Guest.php
src/Login/Controller/Login/ProcessAuthHash.php
src/Login/Controller/Login/Validate.php
src/Login/Controller/Login/ValidatePost.php
src/Login/Model/CheckoutConfigProvider.php
src/Payment/view/frontend/templates/minicart-button.phtml
src/Payment/view/frontend/templates/payment-link-product-page.phtml
src/Payment/view/frontend/web/js/amazon-product-add.js
src/Payment/view/frontend/web/js/view/payment/method-renderer/amazon-payment-widget.js

Ports updates to login/guest controllers from 2.1.x to 1.2.

Update to 1.x for APS-24

---

src/Core/Block/Adminhtml/System/Config/Form/DeveloperLogs.php
src/Core/Block/Adminhtml/System/Config/SimplePathAdmin.php
src/Core/view/adminhtml/templates/system/config/simplepath_admin.phtml
src/Core/view/adminhtml/web/js/simplepath.js
src/Payment/Gateway/Http/Client/AbstractClient.php

Fixed text as requested and removed redundant call to block in template.

Support issue AP-401

---

composer.json
src/Core/composer.json
src/Login/composer.json
src/Payment/composer.json

Reverts amzn/amazon-payments-magento-2-plugin#334

Revert "AP-422" - as requested by the Magento team to always specify PHP requirements for extension

---

composer.json
marketplace-composer.json
src/Core/Setup/UpgradeData.php
src/Core/composer.json
src/Core/etc/module.xml
src/Login/composer.json
src/Login/etc/module.xml
src/Payment/composer.json
src/Payment/etc/module.xml

Update - fixed php version and incremented module version.

Support Issue AP-422

---

src/Login/Controller/Login/Guest.php
src/Login/Model/CheckoutConfigProvider.php
src/Payment/view/frontend/web/js/view/payment/method-renderer/amazon-payment-widget.js

Ports Login/Guest updates from 2.1.x to 2.0.x

Addresses APS-24

---

src/Core/etc/adminhtml/system.xml
src/Login/etc/adminhtml/system.xml
src/Payment/Gateway/Http/Client/AbstractClient.php

Re: APS-36 - update wording to make it more clear what configuration for Login/popup checkbox does.

Update configuration section wording

---

src/Payment/etc/di.xml

Fixes # AP-71, BUNDLE-1767.
Fixes issue with upgrade / deployment to cloud environment.

Remove new line from text node

---

src/Core/etc/db_schema_whitelist.json

Add db_schema_whitelist.json file

APS-70 - add db_schema_whitelist.json file

---

composer.json

Fixes typo in the composer.json version requirement.

AP-427 - fix version requirement typo

---

src/Payment/etc/di.xml

Update di.xml to remove new lines from text nodes

---

src/Core/etc/db_schema.xml
src/Core/etc/db_schema_whitelist.json
src/Payment/Model/Adapter/AmazonPaymentAdapter.php

Fixes new schema format so that it both creates a clean fresh install and correctly upgrades from 2.2.6 to 2.2.7.

Support Issue APS-87

---

src/Login/Controller/Logout/Index.php
src/Login/Helper/Session.php
src/Login/Observer/AmazonCustomerAuthenticated.php
src/Login/etc/events.xml
src/Payment/Observer/KlarnaKcoOverride.php
src/Payment/etc/frontend/events.xml
src/Payment/view/frontend/web/js/amazon-core.js
src/Payment/view/frontend/web/js/model/storage.js

This prevents the Klarna Checkout module from overriding the Amazon Checkout page when the customer is using PwA.

Add Klarna Checkout Compatibility with event observer (ASD-18)

---

src/Payment/Test/Mftf/ActionGroup/AmazonCheckoutActionGroup.xml
src/Payment/Test/Mftf/ActionGroup/AmazonLoginActionGroup.xml
src/Payment/Test/Mftf/Data/AmazonLoginData.xml
src/Payment/Test/Mftf/Section/AmazonCheckoutSection.xml
src/Payment/Test/Mftf/Section/AmazonLoginSection.xml
src/Payment/Test/Mftf/Test/AmazonCheckoutDeclineTest.xml
src/Payment/Test/Mftf/Test/AmazonCheckoutSuccessTest.xml

Adds 10 MFTF login and checkout tests:
- AmazonCheckoutProductDetail
- AmazonCheckoutCart
- AmazonCheckoutMiniCart
- AmazonCheckoutPage
- AmazonCheckoutCustomer
- AmazonCheckoutDeclinePaymentMethod
- AmazonCheckoutDeclineInvalidPaymentMethod
- AmazonCheckoutDeclineAmazonRejected
- AmazonCheckoutDeclineTransactionTimedOutInstant
- AmazonCheckoutDeclineTransactionTimedOutAutomatic

Add MFTF Tests

---

src/Core/Domain/AmazonAddressDecoratorJp.php
src/Core/Domain/AmazonAddressFactory.php
src/Core/Observer/PaymentConfigSaveAfter.php
src/Core/etc/config.xml
src/Payment/Helper/Address.php

ASD-37: fix error when submitting payment using a Japanese street address

---

src/Core/Domain/AmazonAddressDecoratorJp.php
src/Core/Domain/AmazonAddressFactory.php
src/Payment/Helper/Address.php

ASD-37: backporting Japanese address patch to 2.x branch

---

src/Core/Domain/AmazonAddressDecoratorDe.php

asd-77: fix missing street address for German addresses

---

src/Core/Exception/AmazonServiceUnavailableException.php
src/Payment/Block/CheckoutErrorMessage.php
src/Payment/Controller/Payment/CompleteCheckout.php
src/Payment/Gateway/Command/AmazonAuthCommand.php
src/Payment/Model/Adapter/AmazonPaymentAdapter.php
src/Payment/Model/OrderInformationManagement.php
src/Payment/Plugin/ConfirmOrderReference.php
src/Payment/etc/di.xml
src/Payment/view/frontend/layout/amazon_payments_payment_completecheckout.xml
src/Payment/view/frontend/templates/checkout-error.phtml
src/Payment/view/frontend/web/js/action/place-order.js

This commit implements SCA verification in accordance with Amazon's Amazon Pay Strong Customer Authentication (SCA) Upgrade documentation.

apf-125: Integrate Amazon SCA validation into checkout flow

---

src/Payment/Block/CheckoutErrorMessage.php
src/Payment/Plugin/ConfirmOrderReference.php

ASD-87: Add copyright to new files

---

src/Payment/Block/CheckoutErrorMessage.php
src/Payment/Test/Unit/Gateway/Command/CaptureStrategyCommandTest.php
src/Payment/view/frontend/layout/amazon_payments_payment_completecheckout.xml

ASD-101 - changes from Magento feedback

---

src/Payment/Test/Unit/Gateway/Command/CaptureStrategyCommandTest.php

ASD-101 - feedback from Magento

---

src/Login/view/frontend/templates/oAuthRedirect.phtml
src/Login/view/frontend/web/js/amazon-redirect.js
src/Payment/view/frontend/web/js/view/shipping-address/inline-form.js

Fixes ASD-118 and mitigates ASD-111

M2.2.9 rc3

---

src/Core/Helper/Data.php
src/Core/Model/AmazonConfig.php
src/Login/view/frontend/layout/default.xml
src/Login/view/frontend/web/js/amazon-redirect.js
src/Payment/view/frontend/web/js/amazon-button.js
src/Payment/view/frontend/web/js/amazon-core.js
src/Payment/view/frontend/web/js/model/storage.js
src/Payment/view/frontend/web/js/view/checkout-widget-address.js
src/Payment/view/frontend/web/js/view/payment/method-renderer/amazon-payment-widget.js

ASD-50: replace Core\Helper\Data class with a wrapper around Core\Model\AmazonConfig
ASD-132: improve support for ITP-enabled browsers

integration-20190711

---

src/Login/view/frontend/web/js/amazon-redirect.js
src/Payment/view/frontend/web/js/amazon-button.js
src/Payment/view/frontend/web/js/amazon-core.js
src/Payment/view/frontend/web/js/model/storage.js
src/Payment/view/frontend/web/js/view/checkout-widget-address.js
src/Payment/view/frontend/web/js/view/payment/method-renderer/amazon-payment-widget.js

ASD-132: improve support for ITP-enabled browsers

integration-20190712-21x

---

composer.json
src/Core/Controller/Adminhtml/Alexa/Download.php
src/Core/Controller/Adminhtml/Alexa/GenerateKeys.php
src/Core/Helper/Data.php
src/Core/Logger/AlexaLogger.php
src/Core/Logger/Handler/Alexa.php
src/Core/Model/Alexa.php
src/Core/Model/Config/Backend/Privatekey.php
src/Core/Model/Config/Comment/AlexaPrivateKey.php
src/Core/Model/Config/Comment/AlexaPublicKeyId.php
src/Core/Observer/SalesOrderShipmentTrackAfter.php
src/Core/composer.json
src/Core/etc/adminhtml/events.xml
src/Core/etc/adminhtml/system.xml
src/Core/etc/di.xml
src/Core/etc/events.xml
src/Core/etc/files/amazon-pay-delivery-tracker-supported-carriers.csv
src/Payment/Gateway/Command/CaptureStrategyCommand.php
src/Payment/Test/Mftf/Data/AmazonPaymentData.xml
src/Payment/Test/Mftf/Data/AmazonShipmentData.xml
src/Payment/Test/Mftf/Metadata/amazon_payment_config-meta.xml
src/Payment/Test/Mftf/Test/AmazonAlexaShipmentTest.xml

Adds Alexa Delivery Notifications when creating a shipment tracking number for an order. Includes mapping of carrier titles to Alexa carrier codes and MFTF test.

Alexa Delivery Notifications

---

src/PayV2/Gateway/Validator/GeneralResponseValidator.php
src/PayV2/Model/Adapter/AmazonPayV2Adapter.php
src/PayV2/Model/CheckoutSessionManagement.php

Addresses the following changes to the Checkout Session object keys used during API response parsing:
- webCheckoutDetails updated to webCheckoutDetail
- paymentDetails updated to paymentDetail
- statusDetails updated to statusDetail

APF-176: update keys for Checkout Session object

---

src/PayV2/Controller/Adminhtml/PayV2/Download.php
src/PayV2/Gateway/Validator/GeneralResponseValidator.php
src/PayV2/Model/Adapter/AmazonPayV2Adapter.php
src/PayV2/Model/CheckoutSessionManagement.php
src/PayV2/Model/Config/Comment/PrivateKey.php
src/PayV2/Model/Config/Comment/PublicKeyId.php
src/PayV2/etc/acl.xml

APF-176: hide mailto link in admin panel
APF-176: download private key from admin panel

APF-176: add private key download link and hide mailto link

---

src/Core/Controller/Adminhtml/Simplepath/Poll.php
src/Core/Controller/Simplepath/Listener.php
src/Core/Logger/ExceptionLogger.php
src/Core/Model/AmazonConfig.php
src/Login/Domain/LayoutConfig.php
src/Login/Test/Unit/Model/LayoutConfigTest.php
src/Login/view/frontend/templates/oAuthRedirect.phtml
src/Payment/Controller/Payment/CompleteCheckout.php
src/Payment/Gateway/Command/AmazonAuthCommand.php
src/Payment/Gateway/Command/CaptureStrategyCommand.php
src/Payment/Plugin/ConfirmOrderReference.php
src/Payment/Plugin/ShippingInformationManagement.php
src/Payment/view/frontend/web/css/source/_module.less
src/Payment/view/frontend/web/js/model/storage.js
src/Payment/view/frontend/web/js/view/checkout-revert.js
src/Payment/view/frontend/web/js/view/checkout-widget-address.js
src/Payment/view/frontend/web/js/view/shipping-address/inline-form.js
src/Payment/view/frontend/web/template/checkout-widget-address.html

This PR addresses the following issues:
ASD-209: hide account creation form when shipping address form is hidden
ASD-211: whitespace changes
ASD-218: MS Edge: fix "return to standard checkout"

Integration 20191108

---

src/PayV2/Plugin/BackendFieldDependence.php

ASD-220: fix duplicate config fields being shown

ASD-220: fix duplicate config fields being shown

---

src/Login/view/frontend/web/js/amazon-redirect.js
src/Payment/view/frontend/web/js/amazon-button.js
src/Payment/view/frontend/web/js/amazon-core.js
src/Payment/view/frontend/web/js/model/storage.js
src/Payment/view/frontend/web/js/view/checkout-widget-address.js
src/Payment/view/frontend/web/js/view/payment/method-renderer/amazon-payment-widget.js

This PR backports the ITP-related (ASD-132) changes to the 1.x (Magento 2.1.x) branch.

ASD-212_1.x

---

README.md

This is a very minor grammatical change to README.md

---

src/Payment/view/frontend/web/js/action/place-order.js

Fixes issue where cart cache shows content after checkout.# .

ASD-253: invalidate cart cache when processing payment

---

composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

Fixes # .
ASD-277: Excluded *.payments-amazon.com/checkout.js from minification

version increase to v1.0.2-beta

---

composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

Fixes # .
Digital Goods implementation
Billing address retrieval for EU (from payment method) and US (copied over from shipping address)

version increase to 1.1.0

---

src/Payment/view/frontend/web/js/view/shipping.js

ASD-345: Fixed set shipping information in standard checkout

---

src/PayV2/Test/Mftf/ActionGroup/AmazonCheckoutActionGroup.xml
src/PayV2/Test/Mftf/ActionGroup/AmazonLoginActionGroup.xml
src/PayV2/Test/Mftf/Data/AmazonAccountData.xml
src/PayV2/Test/Mftf/Data/AmazonButtonConfigData.xml
src/PayV2/Test/Mftf/Data/AmazonPaymentConfigData.xml
src/PayV2/Test/Mftf/Data/AmazonPaymentData.xml
src/PayV2/Test/Mftf/Metadata/amazon_payment_v1_config-meta.xml
src/PayV2/Test/Mftf/Metadata/amazon_payment_v2_config-meta.xml
src/PayV2/Test/Mftf/Section/AmazonButtonSection.xml
src/PayV2/Test/Mftf/Section/AmazonCheckoutSection.xml
src/PayV2/Test/Mftf/Section/AmazonPageSection.xml
src/PayV2/Test/Mftf/Test/AmazonAddressTest.xml
src/PayV2/Test/Mftf/Test/AmazonButtonTest.xml
src/PayV2/Test/Mftf/Test/AmazonCheckoutTest.xml
src/PayV2/Test/Mftf/Test/AmazonLoginTest.xml
src/PayV2/registration.php

ASD-322: Testing V1 and V2 Run Separately
ASD-323: Testing Login to Pay
ASD-324: Testing Select Address
ASD-325: Testing Place a Successful Order

Feature MFTF

---

src/Payment/Gateway/Config/Config.php
src/Payment/Model/Adapter/AmazonPaymentAdapter.php
src/Payment/etc/di.xml

ASD-308: Deleted confirmOrderReference call from authorize
ASD-321: Disabling partial capture for EU/UK

ASD-308 & ASD-321 (Split Shipments)

---

README.md

Adding alexa section in readme

---

README.md

Moving alexa section above Branch info table

---

README.md

Update V2 Readme

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

version increase to 2.0.2 (V2checkout)

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

version increase to 1.2.1 (v2checkout-1.2.x)

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

version increase to 1.3.0

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

version increase to 1.3.1

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

V2Checkout - Version increase to 2.1.0

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

version increase to 1.4.0 (V2checkout-1.2.x)

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

version increase to 2.1.1 (v2Checkout)

---

configuration.html

Store Name default value change in public docs

---

login.html

Update docs with new LWA reference

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

version increase to 2.1.3

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

version increase to 2.1.4

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

version increase to 1.4.1

---

README.md

Added V2checkout installation instructions

---

src/Payment/view/frontend/web/js/messages.js
src/Payment/view/frontend/web/js/view/checkout-widget-address.js
src/Payment/view/frontend/web/js/view/shipping.js

ASD-453 fixes shipping address validation and messaging when it fails

---

composer.json
src/PayV2/Client/Client.php
src/PayV2/Client/ClientFactoryInterface.php
src/PayV2/Gateway/Response/AuthorizationSaleHandler.php
src/PayV2/Gateway/Response/SettlementHandler.php
src/PayV2/Gateway/Validator/GeneralResponseValidator.php
src/PayV2/Model/Adapter/AmazonPayV2Adapter.php
src/PayV2/Model/AsyncManagement/Charge.php
src/PayV2/Model/AsyncManagement/Refund.php
src/PayV2/Model/CheckoutSessionManagement.php
src/PayV2/composer.json

APF-222 1.2.x migrates to V2 of the Amazon Pay API from legacy API

---

composer.json
src/PayV2/Client/Client.php
src/PayV2/Client/ClientFactoryInterface.php
src/PayV2/Gateway/Response/AuthorizationSaleHandler.php
src/PayV2/Gateway/Response/SettlementHandler.php
src/PayV2/Gateway/Validator/GeneralResponseValidator.php
src/PayV2/Model/Adapter/AmazonPayV2Adapter.php
src/PayV2/Model/AsyncManagement/Charge.php
src/PayV2/Model/AsyncManagement/Refund.php
src/PayV2/Model/CheckoutSessionManagement.php
src/PayV2/composer.json

APF-222 migrates to V2 of the Amazon Pay API from legacy API

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

Fixes # .
- APIv2 upgrade
- closeChargePermission fix
- EU5 declined messages translations

version increase to 1.5.0

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

Fixes # .
- APIv2 upgrade
- closeChargePermission fix
- EU5 declined messages translations

version increase to 2.2.0

---

src/PayV2/Domain/AmazonAddress.php
src/PayV2/Domain/AmazonAddressDecoratorDe.php
src/PayV2/Domain/AmazonAddressInterface.php
src/PayV2/Helper/Address.php

Reverts amzn/amazon-payments-magento-2-plugin#853

Revert "Asd 488 v2checkout 1.2.x"

---

src/PayV2/Domain/AmazonAddress.php
src/PayV2/Domain/AmazonAddressDecoratorDe.php
src/PayV2/Domain/AmazonAddressDecoratorJp.php
src/PayV2/Domain/AmazonAddressInterface.php
src/PayV2/Helper/Address.php

ASD-488 adds methods to Jp address decorator

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

Fixes # .
- fix refund
- fix de addresses handling

version increase to 1.5.1

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

version increase to 1.6.0

---

src/Payment/Test/Unit/Gateway/Command/CaptureStrategyCommandTest.php

ASD-508 - additional update from Magento

---

src/PayV2/view/frontend/web/js/view/checkout/summary/grand-total-mixin.js

ASD-501 - update to using PayV2 js

---

src/Payment/Test/Mftf/Section/AmazonLoginSection.xml

ASD-508 login MFTF fix

---

src/PayV2/Gateway/Config/Config.php
src/PayV2/Gateway/Request/AuthorizationSaleRequestBuilder.php
src/PayV2/Gateway/Request/SettlementRequestBuilder.php
src/PayV2/Gateway/Response/AuthorizationSaleHandler.php
src/PayV2/Model/Adapter/AmazonPayV2Adapter.php
src/PayV2/Model/CheckoutSessionManagement.php
src/PayV2/Observer/OrderPaymentCapture.php
src/PayV2/Plugin/OrderCurrencyComment.php
src/PayV2/etc/events.xml

Add support for split invoicing

Apf 221 1.2.x

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

Version increase to 2.3.0

---

src/Payment/Test/Mftf/Section/AmazonLoginSection.xml

ASD-508 - update selector to find button

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

version increase to 1.7.0

---

src/Payment/Test/Mftf/Test/AmazonCheckoutSuccessAfterDeclinedTest.xml
src/Payment/Test/Mftf/Test/AmazonCheckoutSuccessAfterSCAAbandonedTest.xml

ASD-512 - re-add tests accidentally removed in conflict resolution

---

src/PayV2/Controller/Checkout/CompleteSession.php

ASD-467 - bypass cache check in DepersonalizeChecker

---

src/PayV2/view/frontend/web/js/amazon-button.js

ASD-490 - do not alter button visibility on Checkout page

---

src/PayV2/Model/CheckoutSessionManagement.php

ASD-500 - remove validator referenced from CV1 that is no longer used

---

src/PayV2/view/frontend/web/js/view/checkout/summary/grand-total-mixin.js

ASD-521 - use V2 js method for determining if in Amazon checkout flow

---

src/PayV2/Gateway/Response/RefundHandler.php

ASD-394 adds AP refund success message

---

README.md

moved V2checkout install instructions pointer

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

Fixes # .
-  Fixes issue with declined transactions displaying incorrectly in Magento Admin.  This issue manifested as declined transactions (visible to the buyer) not being recorded as such in the Magento Admin and leading to some situations where they were not cancelable or actionable by the merchant.

Version Increase, to 2.4.0

---

src/PayV2/Model/AmazonConfig.php
src/PayV2/Test/Mftf/ActionGroup/AmazonLoginActionGroup.xml
src/PayV2/Test/Mftf/Data/AmazonCountryData.xml
src/PayV2/Test/Mftf/Data/AmazonCurrencyData.xml
src/PayV2/Test/Mftf/Data/AmazonPaymentConfigData.xml
src/PayV2/Test/Mftf/Metadata/AmazonCountryConfigMeta.xml
src/PayV2/Test/Mftf/Metadata/AmazonCurrencyConfigMeta.xml
src/PayV2/Test/Mftf/Metadata/amazon_payment_v2_config-meta.xml
src/PayV2/Test/Mftf/Test/AmazonCheckoutDisabledNoButtonV2Test.xml
src/PayV2/Test/Mftf/Test/AmazonCheckoutMulticurrencyCurrencyNoButtonV2Test.xml
src/PayV2/Test/Mftf/Test/AmazonCheckoutMulticurrencyDisabledNoButtonV2Test.xml
src/PayV2/Test/Mftf/Test/AmazonCheckoutMulticurrencySuccessV2Test.xml
src/PayV2/Test/Mftf/Test/AmazonMulticurrencyCheckoutSuccessV2Test.xml
src/PayV2/etc/config.xml
src/PayV2/view/adminhtml/web/js/simplepath-mixin.js

Apf 236 1.2.x

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

Fixes # .
- added multicurrency support

version increase to 1.9.0

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

Fixes # .
- added multicurrency support

version increase to 2.5.0

---

src/PayV2/Test/Mftf/ActionGroup/AmazonLoginActionGroup.xml
src/PayV2/Test/Mftf/Test/AmazonCheckoutMulticurrencySuccessV2Test.xml
src/PayV2/Test/Mftf/Test/AmazonShippingAddressTest.xml

Adds invoicing confirmation, and changes how the tests wait for Amazon hosted pages to load

APF-236 additional

---

src/PayV2/Test/Mftf/ActionGroup/AmazonLoginActionGroup.xml
src/PayV2/Test/Mftf/Test/AmazonAddressTest.xml
src/PayV2/Test/Mftf/Test/AmazonCheckoutMulticurrencySuccessV2Test.xml

Adds invoicing confirmation, and changes how the tests wait for Amazon hosted pages to load

APF-236 1.2.x

---

src/PayV2/Test/Mftf/Data/AmazonCurrencyData.xml

APF-236 - update mftf data node to have unique name

---

src/PayV2/Test/Mftf/ActionGroup/AmazonLoginOnlyActionGroup.xml
src/PayV2/Test/Mftf/Data/AmazonAccountData.xml
src/PayV2/Test/Mftf/Data/AmazonPaymentConfigData.xml
src/PayV2/Test/Mftf/Metadata/AmazonPaymentV2ConfigMeta.xml
src/PayV2/Test/Mftf/Section/AmazonLoginSection.xml
src/PayV2/Test/Mftf/Test/AmazonCheckoutGuestCheckoutDisabledNoButtonV2Test.xml
src/PayV2/Test/Mftf/Test/AmazonCheckoutLoggedInNoGuestButtonV2Test.xml
src/PayV2/Test/Mftf/Test/AmazonSignInButtonDisabledTest.xml
src/PayV2/Test/Mftf/Test/AmazonSignInButtonTest.xml
src/PayV2/Test/Mftf/Test/AmazonSignInCreateAccountTest.xml
src/PayV2/Test/Mftf/Test/AmazonSignInExistingUnlinkedAccountTest.xml
src/PayV2/Test/Mftf/Test/AmazonSignInToExistingTest.xml
src/PayV2/Test/Mftf/Test/AmazonSigninCheckoutSuccessV2Test.xml

APF-224 - add MFTF tests for Sign in with Amazon

---

src/PayV2/Model/CheckoutSessionManagement.php

ASD-516 V2checkout cancels order on any problem with the checkout session

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

Fixes # .
Supporting a new feature for canceling orders if the completeCheckoutession() call fails."

Version increase from 2.5.0 to 2.6.0

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

Supporting a new feature for canceling orders if the completeCheckoutSession() call fails.
Fixes # .

Version increase from 1.9.0 to 1.10.0

---

src/PayV2/Test/Mftf/Test/AmazonInvoiceMultipleCapture.xml
src/PayV2/Test/Mftf/Test/AmazonInvoiceOnlySingleCapture.xml
src/PayV2/Test/Mftf/Test/AmazonSignInToExistingTest.xml

Adds tests for split invoicing and ensuring it isn't allowed in EU.

APF-223 - split invoice tests

---

src/PayV2/Test/Mftf/ActionGroup/AmazonCheckoutActionGroup.xml
src/PayV2/Test/Mftf/Section/AmazonCheckoutSection.xml
src/PayV2/Test/Mftf/Test/AmazonCheckoutReturnToStandardTest.xml

Apf 240 1.2.x

---

src/PayV2/Test/Mftf/ActionGroup/AmazonCheckoutActionGroup.xml
src/PayV2/Test/Mftf/Section/AmazonCheckoutSection.xml
src/PayV2/Test/Mftf/Test/AmazonCheckoutReturnToStandardTest.xml

APF-240 - test Return to Standard Checkout

---

src/PayV2/Test/Mftf/ActionGroup/AmazonAlreadyLoggedInActionGroup.xml
src/PayV2/Test/Mftf/Section/AmazonCheckoutSection.xml
src/PayV2/Test/Mftf/Section/AmazonPageSection.xml
src/PayV2/Test/Mftf/Test/AmazonCheckoutCancelledThenSuccessTest.xml

Apf 237 1.2.x

---

src/PayV2/Test/Mftf/ActionGroup/AmazonCheckoutActionGroup.xml
src/PayV2/Test/Mftf/Section/AmazonPageSection.xml
src/PayV2/Test/Mftf/Test/AmazonCheckoutBuyerCanceledTest.xml
src/PayV2/Test/Mftf/Test/AmazonCheckoutDeclinedV2Test.xml

Apf 263 1.2.x

---

src/Payment/Test/Mftf/Data/AmazonCurrencyData.xml
src/Payment/Test/Mftf/Test/AmazonMulticurrencyTest/AmazonCheckoutMulticurrencyCurrencyNoButtonV2Test.xml
src/Payment/Test/Mftf/Test/AmazonMulticurrencyTest/AmazonCheckoutMulticurrencyDisabledNoButtonV2Test.xml
src/Payment/Test/Mftf/Test/AmazonMulticurrencyTest/AmazonCheckoutMulticurrencySuccessTest.xml

APF-234 - add tests for multicurrency

---

src/PayV2/Block/ProductPagePaymentLink.php

ASD-567 V2checkout does not render button on pdp when product out of stock

---

src/PayV2/Test/Mftf/Test/AmazonSignInToExistingTest.xml

APF-224 - adjust cookie clearing to ensure logged out from Amazon

---

src/PayV2/view/frontend/requirejs-config.js

ASD-582 - disable CV1 mixin to prevent js errors

---

src/Payment/Test/Mftf/Data/AmazonCurrencyData.xml
src/Payment/Test/Mftf/Data/AmazonPaymentData.xml
src/Payment/Test/Mftf/Test/AmazonCheckoutMulticurrencyCurrencyNoButtonTest.xml

Asd 593 3.0.x

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

Fixes # .
- fixes Charge on Order + Automatic configuration
- fixes Cronjob and IPN async handling

version increase to 1.11.0

---

README.md
composer.json
src/PayV2/composer.json
src/PayV2/etc/module.xml

Fixes # .
-   fixes Charge on Order + Automatic configuration
-  fixes Cronjob and IPN async handling

version increase to 2.7.0

---

src/Payment/etc/csp_whitelist.xml

ASD-559 3.0.x adds cloudfront cdn whitelist

---

src/PayV2/Model/CheckoutSessionManagement.php

ASD-591 collects quote totals before placing order

---

src/PayV2/Test/Mftf/ActionGroup/AdminOpenOrderByEntityIdActionGroup.xml
src/PayV2/Test/Mftf/Test/AmazonCheckoutAsyncDeclinedTest.xml
src/PayV2/Test/Mftf/Test/AmazonCheckoutAsyncSuccessTest.xml
src/PayV2/Test/Mftf/Test/AmazonCheckoutCancelledThenSuccessTest.xml

Asd 610 mftf 1.2.x

---

Model/Adapter/AmazonPayAdapter.php
Model/AsyncManagement/AbstractOperation.php
Plugin/LegacyPaymentHandler.php

Fix for creating orders via admin, where payment is not yet set on the order

---

etc/frontend/di.xml

Remove di entry for removed plugin

---

src/Payment/Test/Mftf/ActionGroup/AmazonLoginActionGroup/AmazonLoginPopupActionGroup.xml
src/Payment/Test/Mftf/Suite/AmazonPayCV1Suite.xml
src/Payment/Test/Mftf/Test/AmazonCheckoutDeclineTest/AmazonCheckoutAddressFailureTest.xml
src/Payment/Test/Mftf/Test/AmazonCheckoutDeclineTest/AmazonCheckoutDeclinePaymentMethodTest.xml
src/Payment/Test/Mftf/Test/AmazonCheckoutDeclineTest/AmazonCheckoutSCAAbandonedTest.xml
src/Payment/Test/Mftf/Test/AmazonMulticurrencyTest/AmazonCheckoutMulticurrencyCurrencyNoButtonV2Test.xml

ASD-684 - workarounds for MFTF issues, add test suite

---

configuration.html
swagger.html

Updated URLs, path parameters, and possible response bodies for API updates

Swagger Updates for API Changes

---

configuration.html

ASD-464 - add Sort Order to configuration

---

Controller/Adminhtml/Pay/ResetAutoKey.php

Fix php7.3 issue with variable type hinting

---

CHANGELOG.md
Controller/AutoKeyExchange/Listener.php
Model/Adapter/AmazonPayAdapter.php
README.md
composer.json
etc/csp_whitelist.xml

Integration

---

customisation.html
swagger.html

Update body format for checkout session config object

---

customisation.html
index.html

Add notes on rendering the Amazon Sign In button in a custom location

---

faq.html
index.html
installation.html
swagger.html

2.4.4 notes, transaction ID formats, Swagger response body updates

---

installation.html

Bump minimum required version for Magento 2.4.4

---

configuration.html

Update inaccurate multicurrency information

---

customisation.html
graphql-docs.html
index.html

Include GraphQL documentation

---

configuration.html

Clarify and emphasize wording around order processing regardless of auth

---

configuration.html

ASD-928 - Add sections for configurable cancel URLs

---

Helper/Spc/Cart.php
Helper/Spc/ShippingMethod.php

Credit to JustKampers for the patch

fixes shipping method selection when not available

---

installation.html

Add information about Key Upgrade API to installation section

---

Setup/Patch/Data/PerformKeyUpgrade.php

GH-1188 - Fix bypass of key upgrade process if no CV1 credentials exist

---

Helper/Spc/ShippingMethod.php

APF-391 fixes billing address missing in cheapest method set

---

configuration.html
customisation.html

ASD-1239 - Update Amazon doc links
