- src/Login/Setup/UpgradeSchema.php
- src/Payment/Api/AddressManagementInterface.php
- src/Payment/Setup/UpgradeSchema.php
This prevents an install error when table prefixes are used
> Table names should get canonical name for prefixed tables

- src/Payment/view/frontend/requirejs-config.js
- src/Payment/view/frontend/web/js/model/place-order-mixin.js
- src/Payment/view/frontend/web/template/payment/amazon-payment-widget.html
The Amazon module was not properly tracking Terms agreements when placing the order.
Initially, the HTML template was missing the code to even render the Messages and Checkout Agreements blocks, so I added it back into the template.
However, this did not solve the problem as it now complained about not accepting the agreement even with the checkbox checked.
I created a new mixin for the place-order JavaScript action based on the one added by the Magento_CheckoutAgreements module that correctly injects the agreement selection into the payment data before submitting to the API.
This allows the order to succeed.
> Integrate checkout agreements

- src/Payment/view/frontend/web/js/view/checkout-widget-address.js
- src/Payment/view/frontend/web/js/view/payment/method-renderer/amazon-payment-widget.js
Since a few weeks, the widgets expect (optionally) the scope used at the button level.
> added scope parameter to payment widgets

- src/Payment/Observer/CompleteOrderStatus.php
On our server, we have seen certain circumstances where the source quote for an order was no longer available. Because this observer code tries to get the payment method from the quote rather than the order itself, it was causing a fatal error when the quote couldn't be loaded.
By using the payment method defined on the order itself, we should avoid this problem.
> Fix potential data issues in CompleteOrderStatus observer

- src/Payment/view/frontend/web/js/amazon-core.js
By adding jquery/jquery-storageapi as a require dependency $.cookieStorage is always available. In some instances it is not available, depending on what scripts are used in any given instance.
This is a standard dependency to have when using $.cookieStorage. Searching for $.cookieStorage  in the core codebase shows any time it is in use jquery/jquery-storageapi is a dependency.
> Adjusted amazon-core require deps

- src/Payment/view/frontend/web/js/amazon-button.js
This update forces extension to explicitly use Magento 2 built in Modernizr plugin. Previously it used global object declaration to call it potentially causing problems when a newer, but backward incompatible Modernizr 3.x plugin was also available in addition to built-in 2.x.
> AMAZON-38: Forces extension to explicitly use built in modernizr plugin

- src/Payment/view/frontend/web/js/view/payment/list.js
Originally reported as: "we found out the handling for the InvalidPaymentMethod decline is not handled correctly."
This PR fixes a bug where 'amazon_payment' component instance could not be retrieved because of a layout region index mismatch. Region is not needed to be used here at all, so the fix just changes that to simple getChild call.
> Changed the way how 'amazon_payment' is retrieved

- src/Payment/Model/OrderInformationManagement.php
- src/Payment/Plugin/ShippingInformationManagement.php
This PR is meant to solve following problem:
When user starts, but does not complete the checkout using Amazon Widget, she receives Amazon Order Reference ID which after certain period of time becomes stale. In combination with Magento persistent shopping cart this (becoming stale) causes problems when attempt to complete purchase using "standard" Magento checkout (alternative payment methods). As a result the user is always forwarded from checkout to the "My Account" page.
This PR does two things:
1. It invalidates Amazon Order Reference ID when user decides to switch to standard checkout.
2. aroundSaveAddressInformation plugin checks if user has been logged in using Amazon account and if not skips Reference ID handling.
> Fixes situation where Amazon Reference ID draft state has been expired

- src/Core/Model/Config/SimplePath.php
There's an oversight in the `Amazon\Core\Model\Config\SimplePath` class where a table is being called without using the proper tableName getter. This will fail on any install using table prefixes.
> Use table name getter to add prefix in table call.

- .gitignore
- src/Core/Block/Adminhtml/System/Config/Form/Version.php
- src/Core/Helper/Data.php
- src/Core/Model/Config/SimplePath.php
Fixes # .
From now on the extension uses core module setup_version for version information
Core Helper now has method getVersion() which is from now on the definite source of extension version data (right now it uses Amazon_Core setup_version). All other functions that require this information acquire it from there.
> Extension now uses Amazon_Core setup_version to display version data

- src/Login/view/frontend/templates/login.phtml
- src/Payment/view/frontend/templates/minicart-button.phtml
- src/Payment/view/frontend/templates/payment-link-product-page.phtml
- src/Payment/view/frontend/templates/payment-link.phtml
- src/Payment/view/frontend/web/js/amazon-product-add.js
- src/Payment/view/frontend/web/template/checkout-button.html
This PR attempts to add unique IDs to html blocks that are used for PwA/LwA buttons everywhere on the site, therefor solving an id conflict and a bug which would not allow one of the buttons to work in case there are more than one button on the page.
Internal ref: AMAZON-66
> Use unique id for PwA/LwA buttons

- src/Core/etc/config.xml
It is not an error per se but default configuration lacking on some values that either are required for creating payment button or have custom source model without possible unselected state.
Lets say that we want to programatically configure module for automatic deployment. What are required fields to set up? I can check that by looking in the admin panel. 
I deduct that i have to set all credentials plus "please select" options. The rest is already set.
I set those options. Enable module. Add product to cart and try to pay with Amazon.
As a result i get the following js error:
It comes out that button_color is not set and therefore the null value is send to Amazon. Then I realized that though some options in admin looks like the options are selected, in reality they are not and default …
> Add missing default configuration

- src/Core/etc/adminhtml/system.xml
Fixes problem with exclude categories
_Exclude Categories_ functionality has been temporarily disabled.
> Disabled Exclude Categories admin field

- src/Core/etc/adminhtml/system.xml
Fixes exclusion block from advanced options
Locker exclusion didn't work as intended. Disabled it until the update is available.
> Exclusion block from advanced options disabled

- src/Payment/view/frontend/web/js/view/checkout-revert.js
This PR fixes the problem with payment methods disappearing when switching from Amazon Pay to default payments.
> Reload after reverting to default checkout

- src/Payment/composer.json
You can see this issue when trying to enable or disable a module via the magento script (`magento module:disable Module_Name`).
> Invalid JSON causes problems during unserialization

- src/Payment/view/frontend/web/js/action/populate-shipping-address.js
- src/Payment/view/frontend/web/js/view/checkout-widget-address.js
- src/Payment/view/frontend/web/js/view/shipping-address/inline-form.js
- src/Payment/view/frontend/web/js/view/shipping.js
Fixes #175 Missing province in address blocking checkout.
When selecting an address in the checkout process there might be some shipping address data that is not provided by Amazon Payment but is required by Magento.
In that case the Magento's native form validation is used in order to ask the missing information from the customer.
> Added shipping form validation step for the Amazon Payment in checkout

- src/Core/Block/Config.php
- src/Core/view/frontend/templates/config.phtml
- src/Login/view/frontend/web/js/view/login-button-wrapper.js
This update disables loading of related JS files when both Login with Amazon and Pay with Amazon are disabled from admin.
> Do not load JS files when both LwA and PwA are disabled

- src/Payment/etc/di.xml
Related to Magento 2 team request for B2B compatibility.  Quote related tables should be enabled for use with multi-database structures.
> Update - added split-database support for quote-split related tables

- src/Payment/etc/di.xml
Configuration in di.xml file was missing for split sales table, causing address data to be lost/not saved correctly.
> Update re: AP-369

- src/Core/i18n/de_AT.csv
- src/Core/i18n/de_CH.csv
- src/Core/i18n/de_DE.csv
- src/Core/i18n/en_GB.csv
- src/Core/i18n/en_US.csv
- src/Core/i18n/es_AR.csv
- src/Core/i18n/es_CL.csv
- src/Core/i18n/es_CO.csv
- src/Core/i18n/es_CR.csv
- src/Core/i18n/es_ES.csv
- src/Core/i18n/es_MX.csv
- src/Core/i18n/es_PA.csv
- src/Core/i18n/es_PE.csv
- src/Core/i18n/es_VE.csv
- src/Core/i18n/fr_CA.csv
- src/Core/i18n/fr_FR.csv
- src/Core/i18n/it_CH.csv
- src/Core/i18n/it_IT.csv
- src/Core/view/adminhtml/templates/system/config/simplepath_admin.phtml
- src/Login/i18n/en_US.csv
- src/Payment/i18n/en_US.csv
Per discussion - since 'Back' is already defined in Magento base code, convert admin string read 'Back to register or connect an account' and convert translation strings to translate this updated string instead of 'Back'.
> Update - removed references to 'Back'

- src/Payment/view/frontend/web/js/catalog-add-to-cart.js
A backward compatible alternative for
https://github.com/BearGroup/amazon-payments-magento-2-plugin/commit/d8c317df70a626cf2463072eb3cadfced5c53edc
> Fixes the bug which causes 'Add to Cart' request to be executed twice

- src/Core/etc/config.xml
JP `Widgets.js` URL needed to be adjusted for production. 
Fixes #256.
> Fixing JP Prod Widget List

- src/Core/Logger/Handler/Ipn.php
- src/Core/Logger/IpnLogger.php
- src/Core/Logger/Logger.php
- src/Core/etc/di.xml
- src/Payment/etc/di.xml
Custom loggers were not set up correctly in the di.xml file.  Added base logger classes necessary to type/write custom log.
> Support AP-418 - logger fix for 2.x

- src/Core/composer.json
- src/Login/composer.json
- src/Payment/Test/Mftf/composer.json
- src/Payment/composer.json
Fixes issues with not being able to upgrade beyond Amazon Pay 2.0.12 with php7.0.
> AP-422 - expand php version compatibility

- src/Payment/Model/OrderInformationManagement.php
Removes a redundant setter - when the QuoteLink object is deleted, no longer necessary to explicitly set the quote extension value to null - a value that is no longer acceptable as that setter is expecting an interface type.
> Update re: APS-83

- src/Payment/view/frontend/web/js/amazon-core.js
This fixes mobile sandbox login issues by setting sandbox mode and region.
We are seeing some issues in mobile sandbox mode, where the environment does not propagate properly to Amazon Pay. You will be hanging on the "processing redirect" page because "invalid_grant" as the sign-in happens in sandbox.
> Fix mobile sandbox by explicitly setting environment and region in onAmazonLoginReady callback (ASD-10)

- src/Login/view/frontend/web/js/amazon-redirect.js
amazon-redirect.js only handles successful sign-ins. There is no error (catch) handler defined. In case of issues, a customer would be hanging on this page.
This fix prevents the page from hanging and displays the error message from amazon.Login.authorize.
> Add error handler on "processing redirect" page (ASD-9)

- src/Login/view/frontend/web/js/view/login-button-wrapper.js
- src/Payment/view/frontend/web/js/amazon-button.js
- src/Payment/view/frontend/web/js/amazon-core.js
- src/Payment/view/frontend/web/js/amazon-widgets-loader.js
Fixes #405.
This required refactoring the amazon.AmazonButton widget to use the correct button scope (e.g. LwA vs PwA) and to use the window.onAmazonPaymentsReady callback (since previously Widgets.js loaded synchronously).
> Load login and pay buttons asynchronously (ASD-32)

- src/Core/Model/Config/SimplePath.php
Removes mcrypt since PHP 7.2+ will no longer support it. Fixes openssl_decrypt (via phpseclib AES library) using 256 key length and base64_decode($payload->encryptedPayload).
> Remove mcrypt and fix \phpseclib\Crypt\AES decrypt for SimplePath

- src/Core/composer.json
- src/Login/composer.json
- src/Payment/composer.json
Fixes #552  .
Add PHP 7.3 support to `composer.json` for packages:
*   Package: `amzn/amazon-pay-and-login-with-amazon-core-module`
*  Package: `amzn/login-with-amazon-module`
*  Package: `amzn/amazon-pay-module`
> Add PHP 7.3 support to composer packages

- src/PayV2/view/frontend/web/js/action/place-order.js
This PR addresses the following issues:
ASD-228: fix Magento_CheckoutAgreements blocking payments when terms have already been accepted
> ASD-228: Fix Magento_CheckoutAgreements compatibility

- README.md
- src/Payment/Plugin/CheckoutProcessor.php
- src/Payment/view/frontend/layout/checkout_index_index.xml
Fixes #
the plugin overwrites the shippingAddress JS component. this gives issues with other extensions that also use shippingAddress or try to extend/overwrite the JS component.
Right now, modification of the checkout page's jsLayout is happening in a plugin because it's conditional on $quote->isVirtual(), which must be evaluated at runtime for the current quote.
Solution: moving that conditional to the layout xml using a helper class
This PR address issue described here: https://github.com/amzn/amazon-payments-magento-2-plugin/issues/565
> [ASD-197] Shipping JS implementation improvement 

- src/PayV2/Block/Adminhtml/System/Config/Form/Version.php
Declaration of Amazon\PayV2\Block\Adminhtml\System\Config\Form\Version::render($element) must be compatible with Magento\Framework\Data\Form\Element\Renderer\RendererInterface::render(Magento\Framework\Data\Form\Element\AbstractElement $element)
> ASD-333: Fixed PHP Fatal error

- src/PayV2/Gateway/Response/AuthorizationSaleHandler.php
- src/PayV2/Model/Adapter/AmazonPayV2Adapter.php
- src/PayV2/Model/CheckoutSessionManagement.php
- src/PayV2/view/frontend/templates/config.phtml
- src/PayV2/view/frontend/web/js/model/storage.js
Temporarily use the checkout session id as a placeholder transaction id since we don't get a chargeId back until after completeCheckout is called. Once checkout is complete, update the transaction id with the chargeId.
> APF-222: fix for invoicing issue

- Cron/CleanUpIncompleteSessions.php
- Model/CheckoutSessionManagement.php
> [ASD-1227]: Order in status cancelled on Magento2 (ver. 2.4.6-p5)
